---
linters:
  enable:
  - misspell
  - revive

issues:
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck
    - revive
    
linters-settings:
  revive:
    rules:
      - name: unused-parameter
        severity: warning
        disabled: true    

